routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('datos','DatosController');

app/Datos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Datos extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DatosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Datos;

class DatosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datos=Datos::all();
         return view('datos.index',['datos'=>$datos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('datos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dato=new Datos();
        $dato->nombre=$request->nombre;
        $dato->apellidopaterno=$request->apellidopaterno;
        $dato->apellidomaterno=$request->apellidomaterno;
        $dato->fechanacimiento=$request->fechanacimiento;


        if ($dato->save())
        {
            return redirect('/datos');
        }
        else
        {
            return view('datos.create');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dato=Datos::find($id);
        return view('datos.edit',['dato'=>$dato]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $dato=new Datos();
        $dato->nombre=$request->nombre;
        $dato->apellidopaterno=$request->apellidopaterno;
        $dato->apellidomaterno=$request->apellidomaterno;
        $dato->fechanacimiento=$request->fechanacimiento;


        if ($dato->save())
        {
            return redirect('/datos');
        }
        else
        {
            return view('datos.edit',['dato'=>$dato]);
        }
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/datos/create.blade.php
@extends('layouts.app')

@section('content')

<form action="{{route('datos.store')}}" method="POST">
@csrf
<div class="container">
  <div class="form-group">
    <input type="text" class="form-control" name="nombre" placeholder="Nombre">
  </div>
  <div class="form-group">
    <input type="text" class="form-control" name="apellidopaterno" placeholder="Apellido Paterno">
  </div>
  <div class="form-group">
    <input type="text" class="form-control" name="apellidomaterno" placeholder="Apellido Materno">
  </div>
  <div class="form-group">
    <input type="text" class="form-control" name="fechanacimiento" placeholder="Fecha de Nacimiento">
  </div>
  <center><button type="submit" class="btn btn-primary col-md-4">Guardar</button></center>
</div>
</form>

@endsection

resources/views/datos/edit.blade.php
@extends('layouts.app')

@section('content')

<form action="{{route('datos.update',$dato->id)}}" method="POST">
{{method_field('PATCH')}}
@csrf
<div class="container">
  <div class="form-group">
    <input type="text" class="form-control" name="nombre" value="{{$dato->nombre}}" placeholder="Nombre">
  </div>
  <div class="form-group">
    <input type="text" class="form-control" name="apellidopaterno" value="{{$dato->apellidopaterno}}" placeholder="Apellido Paterno">
  </div>
  <div class="form-group">
    <input type="text" class="form-control" name="apellidomaterno" value="{{$dato->apellidomaterno}}" placeholder="Apellido Materno">
  </div>
  <div class="form-group">
    <input type="text" class="form-control" name="fechanacimiento" value="{{$dato->fechanacimiento}}" placeholder="Fecha de Nacimiento">
  </div>
  <center><button type="submit" class="btn btn-primary col-md-4">Guardar</button></center>
</div>
</form>

@endsection

resources/views/datos/index.blade.php
@extends('layouts.app')

@section('content')

<div class="text-center">
  <h1>Pacientes</h1>
  <br>
</div>

<div class="container">
  <table class="table table-bordered">
    <thead class="thead-dark">
     <tr>
       <th>ID</th>
       <th>NOMBRE</th>
       <th>APELLIDO PATERNO</th>
       <th>APELLIDO MATERNO</th>
       <th>FECHA NACIMIENTO</th>
       <th>ACCIÓN</th>
     </tr>
    </thead>
    <tbody>
    @foreach($datos as $dato)
    </tr>
      <td>{{$dato->id}}</td>
      <td>{{$dato->nombre}}</td>
      <td>{{$dato->apellidopaterno}}</td>
      <td>{{$dato->apellidomaterno}}</td>
      <td>{{$dato->fechanacimiento}}</td>
      <td>
        <a href="{{url('/datos/'.$dato->id.'/edit')}}" class="btn btn-link">Editar</a>
      </td>
    </tr>
    @endforeach
    </tbody>
  </table>
  <center><a class="btn btn-primary col-md-4" href="{{url('/datos/create')}}">Agregar</a></center>
</div>


@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('datos.index') }}">{{ __('Pacientes') }}</a>
                                </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>